baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Redis - So Much More than a Cache"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "true"
uglyurls = "true"
enableEmoji = true
[deployment]
[[deployment.targets]]
# S3
URL = "s3://aws-workshop.redislabs.com/hugo"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
#  Cache static assets for 1 year.
# cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
#  Cache static assets for 1 year.
# cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "Toby Ferguson"
  # Description of the site, will be used in meta information
  description = "Solving Data Challenges in Cloud Applications with Redis"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fas fa-university'></i> Redis University"
url = "https://university.redislabs.com/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-trash-alt'></i> Cleanup"
url = "/cleanup.html"
[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = false
